# Generated by Django 5.2.5 on 2025-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['subject'], 'permissions': [('can_manage_messages', 'Может управлять сообщениями')]},
        ),
    ]
