# Generated by Django 5.2.7 on 2025-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
        ),
    ]
