# Generated by Django 5.2.5 on 2025-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_recipient_options_recipient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['full_name'], 'permissions': [('can_manage_recipients', 'Может управлять получателями')], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
    ]
