# Generated by Django 5.2.5 on 2025-10-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-start_datetime'], 'permissions': [('can_manage_mailings', 'Может управлять рассылками')]},
        ),
        migrations.AlterModelOptions(
            name='mailingattempt',
            options={'ordering': ['-attempted_at'], 'permissions': [('can_manage_attempts', 'Может управлять попытками рассылки')]},
        ),
    ]
